id: PC2047C5C
initial_creation_type: input
source_metadata:
  title: Machik Labdrön Series
  language: pt
  description: 'Texts by and about Machik Labdrön (ma gcig lab sgron, 1031–1129 or
    1055–1149), the consort of Padampa Sangye and principal holder of the Chöd lineage:'
  volume:
    325a30667f844d648631af720548651d:
      title: 'Cutting through the Four Demons in Absolute Space: A Praise of Machik
        Labdrön'
      parent: Praise
    35d1b07a439a424583592e10b271e871:
      title: Prayer to Machik Labdrön
      parent: Prayers
created_at: '2022-03-01T00:43:01.495134'
last_modified_at: '2022-03-01T00:43:01.495136'
